-- TMDB sync support: store film/person metadata and film credits (cast/crew).

-- Film: poster + sync timestamp.
ALTER TABLE public.film
  ADD COLUMN IF NOT EXISTS poster_path text,
  ADD COLUMN IF NOT EXISTS poster_url text,
  ADD COLUMN IF NOT EXISTS tmdb_last_synced_at timestamp with time zone;

-- Person: TMDB identifier + photo.
ALTER TABLE public.person
  ADD COLUMN IF NOT EXISTS tmdb_id integer,
  ADD COLUMN IF NOT EXISTS profile_path text,
  ADD COLUMN IF NOT EXISTS profile_url text,
  ADD COLUMN IF NOT EXISTS external_ids jsonb,
  ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS person_tmdb_id_key ON public.person (tmdb_id);

-- Film credits: denormalized cast/crew roles for ergonomic nominee selection + display.
CREATE TABLE IF NOT EXISTS public.film_credit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  film_id bigint NOT NULL REFERENCES public.film(id) ON DELETE CASCADE,
  person_id bigint NOT NULL REFERENCES public.person(id) ON DELETE CASCADE,
  credit_type text NOT NULL,
  department text,
  job text,
  character text,
  cast_order integer,
  tmdb_credit_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT film_credit_type_check CHECK (credit_type IN ('CAST','CREW'))
);

CREATE INDEX IF NOT EXISTS film_credit_film_id_idx ON public.film_credit (film_id);
CREATE INDEX IF NOT EXISTS film_credit_person_id_idx ON public.film_credit (person_id);
CREATE UNIQUE INDEX IF NOT EXISTS film_credit_unique_tmdb
  ON public.film_credit (film_id, tmdb_credit_id)
  WHERE tmdb_credit_id IS NOT NULL;

