// Theme token map consumed by Mantine's cssVariablesResolver.
// Keep raw visual literals centralized here; the app should consume CSS variables only.

export const foTokens = {
  "--fo-avatar-size-sm": `22px`,
  "--fo-blur-sm": `6px`,
  "--fo-border": `rgba(var(--fo-ivory-rgb), 0.12)`,
  "--fo-border-width": `1px`,
  "--fo-border-width-strong": `2px`,
  // Shared hit targets (used for small icon buttons in tight UI like rails).
  "--fo-hit-size-sm": `var(--fo-control-height)`,
  // Primary button micro-states (keep tokens here so UI behavior stays theme-driven).
  "--fo-button-primary-border": `color-mix(in oklab, var(--fo-gold-primary) 72%, black)`,
  "--fo-button-primary-border-hover": `color-mix(in oklab, var(--fo-gold-primary) 62%, black)`,
  "--fo-button-primary-hover": `color-mix(in oklab, var(--fo-gold-primary) 92%, black)`,
  "--fo-button-primary-active": `color-mix(in oklab, var(--fo-gold-primary) 84%, black)`,
  "--fo-card-gap": `var(--fo-space-sm)`,
  "--fo-charcoal-7": `#222222`,
  "--fo-charcoal-8": `#171717`,
  "--fo-charcoal-9": `#0d0d0d`,
  "--fo-charcoal-rgb": `13, 13, 13`,
  "--fo-control-height": `32px`,
  "--fo-control-padding-x": `12px`,
  "--fo-danger": `#b34b42`,
  "--fo-db-backIconSize": `18px`,
  "--fo-db-backSize": `60px`,
  "--fo-db-buckleBackdropExtra": `180px`,
  "--fo-db-buckleContentMin": `120px`,
  "--fo-db-buckleGap": `var(--fo-space-dense-2)`,
  "--fo-db-buckleHighlightTop": `var(--fo-space-2)`,
  "--fo-db-buckleMax-default": `240px`,
  "--fo-db-clock-font": `16px`,
  "--fo-db-header-font": `14px`,
  "--fo-db-headerHeight": `64px`,
  "--fo-db-headerPadX": `14px`,
  "--fo-db-headerRight-gap": `14px`,
  "--fo-db-meta-font": `12px`,
  "--fo-db-miniLabel-font": `9px`,
  "--fo-db-miniNumber-font": `var(--fo-font-size-xs)`,
  "--fo-db-miniStat-minWidth": `54px`,
  "--fo-db-mobileBottomBarHeight": `52px`,
  "--fo-db-mobileBottomBarPadX": `var(--fo-space-8)`,
  "--fo-db-mobileIconSize": `44px`,
  "--fo-db-mobilePadX": `var(--fo-space-xs)`,
  "--fo-db-rosterUnitDivisor": `6.25`,
  "--fo-db-mobileRailBtn-height": `40px`,
  "--fo-db-mobileRailBtn-iconSize": `20px`,
  "--fo-db-mobileRailBtn-radius": `var(--fo-radius-large)`,
  "--fo-db-mobileRailBtn-width": `52px`,
  "--fo-db-pauseIconSize": `20px`,
  "--fo-db-pauseSize": `64px`,
  "--fo-db-pill-font": `10px`,
  "--fo-db-pill-paddingX": `var(--fo-space-dense-1)`,
  "--fo-db-pill-rowHeight": `16px`,
  "--fo-db-skipLink-paddingX": `var(--fo-space-xs)`,
  "--fo-db-skipLink-paddingY": `var(--fo-space-dense-2)`,
  "--fo-db-skipLink-radius": `10px`,
  "--fo-db-skipLink-shadow": `0 10px 22px rgba(var(--fo-charcoal-rgb), 0.14)`,
  "--fo-db-skipLink-x": `var(--fo-space-xs)`,
  "--fo-db-skipLink-y": `var(--fo-space-dense-2)`,
  "--fo-db-timer-font": `24px`,
  "--fo-db-token-borderWidth": `var(--fo-border-width-strong)`,
  "--fo-db-tokenSize": `33px`,
  "--fo-db-tokenWrapHeight": `44px`,
  "--fo-db-userText-maxWidth": `160px`,
  "--fo-db-wing-gap": `var(--fo-space-dense-2)`,
  "--fo-focus-ring-width": `2px`,
  "--fo-font-size-hero-title": `30px`,
  "--fo-font-size-lg": `24px`,
  "--fo-font-size-md": `18px`,
  "--fo-font-size-sm": `14px`,
  "--fo-font-size-xl": `32px`,
  "--fo-font-size-xs": `12px`,
  "--fo-font-weight-black": `900`,
  "--fo-font-weight-extrabold": `800`,
  "--fo-font-weight-bold": `700`,
  "--fo-font-weight-semibold": `600`,
  "--fo-font-weight-medium": `500`,
  "--fo-font-weight-regular": `400`,
  "--fo-gold": `var(--fo-gold-primary)`,
  "--fo-gold-primary": `#d4af37`,
  "--fo-gold-rgb": `212, 175, 55`,
  "--fo-gold-wash": `#efe6d0`,
  "--fo-gutter-desktop": `var(--fo-space-md)`,
  "--fo-gutter-mobile": `var(--fo-space-xs)`,
  "--fo-gutter-tablet": `var(--fo-space-sm)`,
  "--fo-heading-h1-size": `var(--fo-font-size-xl)`,
  "--fo-heading-h2-size": `var(--fo-font-size-lg)`,
  "--fo-heading-h3-size": `var(--fo-font-size-md)`,
  "--fo-heading-h4-size": `var(--fo-font-size-sm)`,
  "--fo-icon-size-sm": `var(--fo-font-size-sm)`,
  "--fo-icon-size-md": `var(--fo-font-size-md)`,
  "--fo-ivory": `#f7f8fc`,
  "--fo-ivory-neutral": `var(--fo-ivory)`,
  "--fo-ivory-rgb": `247, 248, 252`,
  "--fo-ivory-warm": `var(--fo-ivory)`,
  "--fo-ivory-step-1": `#f2f3f7`,
  "--fo-ivory-step-2": `#eeeff2`,
  "--fo-ivory-step-3": `#e9eaee`,
  "--fo-layout-authMaxWidth": `980px`,
  "--fo-layout-fieldBasis-lg": `420px`,
  "--fo-layout-fieldBasis-md": `360px`,
  "--fo-layout-fieldBasis-sm": `260px`,
  "--fo-layout-fieldMin-lg": `260px`,
  "--fo-layout-fieldMin-md": `240px`,
  "--fo-layout-fieldMin-sm": `220px`,
  "--fo-layout-formMaxWidth": `520px`,
  "--fo-layout-maxWidth": `1200px`,
  "--fo-layout-sidebarWidth": `340px`,
  "--fo-layout-sidebarWidthNarrow": `300px`,
  "--fo-layout-wizardStepperWidth": `320px`,
  "--fo-layout-wizardStepperWidthCompact": `260px`,
  "--fo-letterSpacing-tight": `0.01em`,
  "--fo-letterSpacing-subtle": `0.02em`,
  "--fo-letterSpacing-meta": `0.04em`,
  "--fo-letterSpacing-tracked": `0.06em`,
  "--fo-letterSpacing-eyebrow": `0.08em`,
  "--fo-letterSpacing-rail": `0.09em`,
  "--fo-line-height-body": `1.5`,
  "--fo-line-height-h1": `1.12`,
  "--fo-line-height-h2": `1.2`,
  "--fo-line-height-h3": `1.25`,
  "--fo-line-height-h4": `1.25`,
  "--fo-line-height-meta": `1.3`,
  "--fo-line-height-tight": `1.1`,
  "--fo-opacity-muted-1": `0.92`,
  "--fo-opacity-muted-2": `0.85`,
  "--fo-pill-padding-x": `6px`,
  "--fo-pill-padding-y": `var(--fo-space-hairline)`,
  "--fo-press-offset": `0.5px`,
  "--fo-radius-large": `12px`,
  "--fo-radius-medium": `8px`,
  "--fo-radius-pill": `999px`,
  "--fo-radius-small": `6px`,
  "--fo-section-gap": `var(--fo-space-md)`,
  "--fo-shadow-card": `0 1px 0 rgba(255, 255, 255, 0.03) inset,
    0 10px 24px rgba(0, 0, 0, 0.22)`,
  "--fo-shadow-card-focus": `0 0 0 var(--fo-focus-ring-width) color-mix(in srgb, var(--accent) 55%, transparent),
    0 1px 0 rgba(255, 255, 255, 0.03) inset,
    0 10px 24px rgba(0, 0, 0, 0.22)`,
  "--fo-shadow-card-hover": `0 1px 0 rgba(255, 255, 255, 0.05) inset,
    0 14px 34px rgba(0, 0, 0, 0.28)`,
  "--fo-shadow-draft-pillFocus": `0 0 0 var(--fo-border-width-strong) rgba(var(--fo-gold-rgb), 0.45),
    0 10px 22px rgba(var(--fo-charcoal-rgb), 0.1)`,
  "--fo-shadow-draft-pillHover-dark": `0 12px 26px rgba(0, 0, 0, 0.35),
    0 0 18px rgba(var(--fo-gold-rgb), 0.16),
    0 0 0 var(--fo-border-width) rgba(var(--fo-gold-rgb), 0.32)`,
  "--fo-shadow-draft-pillHover-light": `0 10px 22px rgba(var(--fo-charcoal-rgb), 0.12),
    0 0 0 var(--fo-border-width) rgba(var(--fo-gold-rgb), 0.28)`,
  "--fo-shadow-dragging": `0 6px 18px rgba(0, 0, 0, 0.18)`,
  "--fo-shadow-focusRing-gold": `0 0 0 var(--fo-focus-ring-width) rgba(var(--fo-gold-rgb), 0.4)`,
  "--fo-shadow-focusRing-gold-strong": `0 0 0 var(--fo-border-width-strong) rgba(var(--fo-gold-rgb), 0.45)`,
  "--fo-shadow-focusRing-neutral-soft-dark": `0 0 0 var(--fo-border-width-strong) rgba(var(--fo-ivory-rgb), 0.16)`,
  "--fo-shadow-focusRing-neutral-soft-light": `0 0 0 var(--fo-border-width-strong) rgba(var(--fo-charcoal-rgb), 0.18)`,
  "--fo-shadow-focusRing-neutral-strong-dark": `0 0 0 var(--fo-border-width-strong) rgba(var(--fo-ivory-rgb), 0.2)`,
  "--fo-shadow-focusRing-neutral-strong-light": `0 0 0 var(--fo-border-width-strong) rgba(var(--fo-charcoal-rgb), 0.22)`,
  "--fo-shadow-hero-dark": `0 0 0 1px rgba(0, 0, 0, 0.06) inset,
    0 1px 0 rgba(255, 255, 255, 0.55) inset,
    0 18px 56px rgba(0, 0, 0, 0.12),
    0 10px 24px rgba(0, 0, 0, 0.07)`,
  "--fo-shadow-hero-light": `0 0 0 1px rgba(255, 255, 255, 0.08) inset,
    0 1px 0 rgba(255, 255, 255, 0.06) inset,
    0 18px 56px rgba(0, 0, 0, 0.14),
    0 10px 24px rgba(0, 0, 0, 0.08)`,
  "--fo-shadow-adminNextStep": `0 12px 30px rgba(0, 0, 0, 0.12)`,
  "--fo-shadow-updates": `0 1px 0 rgba(255, 255, 255, 0.02) inset,
    0 6px 16px rgba(0, 0, 0, 0.16)`,
  "--fo-space-0": `0px`,
  "--fo-space-2": `2px`,
  "--fo-space-4": `4px`,
  "--fo-space-8": `8px`,
  "--fo-space-dense-1": `5px`,
  "--fo-space-dense-2": `10px`,
  "--fo-space-hairline": `1px`,
  "--fo-space-lg": `32px`,
  "--fo-space-md": `24px`,
  "--fo-space-sm": `16px`,
  "--fo-space-xs": `12px`,
  "--fo-surface-card-hero": `var(--fo-charcoal-8)`,
  "--fo-surface-card-primary": `var(--fo-charcoal-8)`,
  "--fo-surface-page": `var(--fo-charcoal-9)`,
  "--fo-surface-pill": `var(--fo-charcoal-7)`,
  "--fo-text-deemphasized": `rgba(var(--fo-ivory-rgb), 0.6)`,
  "--fo-text-onGold": `var(--fo-charcoal-9)`,
  "--fo-text-primary": `var(--fo-ivory)`,
  "--fo-text-primary-rgb": `var(--fo-ivory-rgb)`,
  "--fo-tip-bar-paddingX": `var(--fo-space-dense-2)`,
  "--fo-tip-bar-paddingY": `var(--fo-space-8)`,
  "--fo-tip-body-padding": `var(--fo-space-xs)`,
  "--fo-tip-card-gap": `var(--fo-space-xs)`,
  "--fo-tip-poster-height": `108px`,
  "--fo-tip-poster-radius": `var(--fo-radius-large)`,
  "--fo-tip-poster-shadow": `0 12px 30px rgba(0, 0, 0, 0.22)`,
  "--fo-tip-poster-width": `72px`,
  "--fo-tip-width": `340px`,
  "--fo-z-overlay-2": `2`,
  // Alpha tokens (avoid raw numeric literals in CSS; keep values centralized).
  "--fo-alpha-00": `0`,
  "--fo-alpha-02": `0.02`,
  "--fo-alpha-03": `0.03`,
  "--fo-alpha-04": `0.04`,
  "--fo-alpha-05": `0.05`,
  "--fo-alpha-06": `0.06`,
  "--fo-alpha-08": `0.08`,
  "--fo-alpha-10": `0.1`,
  "--fo-alpha-12": `0.12`,
  "--fo-alpha-14": `0.14`,
  "--fo-alpha-16": `0.16`,
  "--fo-alpha-18": `0.18`,
  "--fo-alpha-20": `0.2`,
  "--fo-alpha-22": `0.22`,
  "--fo-alpha-24": `0.24`,
  "--fo-alpha-25": `0.25`,
  "--fo-alpha-26": `0.26`,
  "--fo-alpha-28": `0.28`,
  "--fo-alpha-32": `0.32`,
  "--fo-alpha-35": `0.35`,
  "--fo-alpha-40": `0.4`,
  "--fo-alpha-45": `0.45`,
  "--fo-alpha-50": `0.5`,
  "--fo-alpha-55": `0.55`,
  "--fo-alpha-60": `0.6`,
  "--fo-alpha-65": `0.65`,
  "--fo-alpha-70": `0.7`,
  "--fo-alpha-72": `0.72`,
  "--fo-alpha-75": `0.75`,
  "--fo-alpha-78": `0.78`,
  "--fo-alpha-80": `0.8`,
  "--fo-alpha-100": `1`,
  "--mantine-color-blue-filled": `var(--fo-gold-primary)`,
  "--mantine-color-blue-filled-hover": `var(--fo-gold-primary)`,
  "--mantine-color-blue-light-color": `var(--fo-text-primary)`,
  "--mantine-color-blue-light-hover": `var(--fo-surface-pill)`,
  "--mantine-color-blue-outline": `var(--fo-border)`,
  "--mantine-color-blue-outline-hover": `var(--fo-surface-pill)`,
  "--mantine-primary-color-contrast": `var(--fo-text-onGold)`,
  "--mantine-primary-color-filled": `var(--fo-gold-primary)`,
  "--mantine-primary-color-filled-hover": `var(--fo-gold-primary)`,
  "--mantine-primary-color-light": `var(--fo-surface-pill)`,
  "--mantine-primary-color-light-color": `var(--fo-text-primary)`,
  "--mantine-primary-color-light-hover": `var(--fo-surface-pill)`,
  "--mantine-primary-color-outline": `var(--fo-border)`,
  "--mantine-primary-color-outline-hover": `var(--fo-surface-pill)`
} as const;

export type FoTokenName = keyof typeof foTokens;
